### ISSUE TITLE
Show Latest Scalactic 3.0.5

### ISSUE THREAD

**Issue by cheeseng** [scalatest/scalactic-website#13]
Scalactic 3.0.5 is released:

https://github.com/scalatest/scalatest/releases/tag/release-3.0.5

We should update website to show 3.0.5 on its front page and include release note for 3.0.5.

**Comment by plinlor** [comment]
https://github.com/scalatest/scalactic-website/pull/14

**Comment by plinlor** [comment]
Merged by Bill a day ago, so I'm closing this issue.
