### ISSUE TITLE
website https://www.scalactic.org/ is down

### ISSUE THREAD

**Issue by SebMini** [scalatest/scalactic-website#68]
Hello,
It has been a while now than the web site https://www.scalactic.org/ is down. Is this normal ? 
Is this the corresponding project ? I will try to build the site locally but that would be nice to host https://www.scalactic.org/ again.

Sorry If I am off topic.

Thanks for your response.

**Comment by cheeseng** [comment]
Hi @SebMini We have brought it back, thanks for reporting!

**Comment by SebMini** [comment]
Thanks you !
